import type { Metadata } from "next";
import Header from "./ui/header";
import Footer from "./ui/footer";
import "./style.css";
import { validateRequest } from "@/lib/auth";

export const metadata: Metadata = {
  title: "Main Page",
  description: "Generated by create next app",
};

export default async function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await validateRequest();
  return (
    <div className=" max-w-screen-xl m-auto px-6">
      <div className="font-lusitana">
        <Header />
      </div>
      <div className="bg-white dark:bg-[#1111] dark:text-slate-400">
        {children}
      </div>
      <Footer user={user} />
    </div>
  );
}
